### ISSUE TITLE
Blank frame when switching media

### ISSUE THREAD

**Issue by mihai-moldovan** [DemolitionStudios/DemolitionMediaHap#1]
I have a GameObject containing One RenderToMeshMaterial Script and 2 Media scripts. 
From another script I play each of the media when needed, setting the render.SourceMedia to the new media. 
All goes well, but most of the times there is a white frame rendered when switching the media.

Below is my source code. As you can see I'm now changing the SourceMedia after the movie starts to play. I also tried switching it in PlayMovie method, before playing the media. The results are the same. 

```
private Media[] movies;
private RenderToMeshMaterial movieRenderer;

 void Start()
    {
        movieRenderer = GetComponent<RenderToMeshMaterial>();
        movies = GetComponents<Media>();
        audioSources = GetComponents<AudioSource>();

        for (int i = 0; i < movies.Length; ++i)
        {
            Media m = movies[i];
            m.Open(m.mediaUrl);
            if (i == 0)
            {
                m.Loops = -1;
            }
            else
            {
                m.Loops = 0;
            }
            m.Events.AddListener(this.OnMediaPlayerEvent);
        }

    }

public void PlayMovie(int index)
    {

        if (movies.Length > index)
        {
            Media oldMovie = movieRenderer.SourceMedia;
            Media movie = movies[index];

            if (oldMovie != movie)
            {
                if (oldMovie != null) oldMovie.Pause();
                movie.Play();
                movie.SeekToTime(0);
            }
        }
    }

public void OnMediaPlayerEvent(Media source, MediaEvent.Type type, MediaError error)
    {
        if (type == MediaEvent.Type.PlaybackStarted || type == MediaEvent.Type.PlaybackResumed)
        {
            movieRenderer.SourceMedia = source;
        }
    }
```

I am using Unity 5.6.0f3 on Windows 10 x64 with the latest windows plugin version (0.9.3)
I've noticed the same behaviour on different machines with ATI Radeon or Nvidia graphics cards.

**Comment by leavittx** [comment]
**Versions prior 0.9.5**
Please make sure that the RenderToMeshMatereal’s FallbackTexture property is set to a transparent texture (a texture with alpha = 0). This is the texture which is used when no video frame is available for render yet. You can either create it programatically or specify a file texture from the Unity Editor.

**Version 0.9.5 and above**
FallbackTexture is now transparent by default. The only thing you have to do to to ensure that the video will be transparent when it doesn’t have a frame to show, is check that the mesh material shader is set to Unlit/Transparent.

**Comment by leavittx** [comment]
@mihai-moldovan Should we finally close this?
