### ISSUE TITLE
Memory leaking

### ISSUE THREAD

**Issue by AliveStenka** [DemolitionStudios/DemolitionMediaHap#4]
After running builds with looping videos for about 2-3 days, memory leaks and so computer freezes. Can the native library code be the issue?

**Comment by paulorenanmelo** [comment]
I am profiling on the Unity Editor, and I get 0.6KB of garbage collector from the Media.Update() loop, which causes a small form-factor pc that I'm testing to overheat and freeze. The fact it's a native library shouldn't affect it, but probably the way the plugin handles it is not optimised enough.
NB: if that's the case I hope the devs will come back to life soon to work on that, or make the project opensource.

**Comment by leavittx** [comment]
Should be fixed in 2020 version now
